import './globals.css';

import type { Metadata } from 'next';
import { Public_Sans } from 'next/font/google';
import { SessionProvider } from 'next-auth/react';

import { Header } from '@/features/naviagation';
import { Toaster } from '@/shared';

const publicSans = Public_Sans({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${publicSans.className} flex min-h-screen flex-col antialiased`}
      >
        <SessionProvider>
          <Header />
          <main className="container flex flex-auto flex-col py-10">
            {children}
          </main>
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
}
